### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by curious-mike-dvc** [TobyMaxham/laravel-dkim#2]
Hi, is it possible to add support for Laravel 9 ?

**Comment by TobyMaxham** [comment]
Hello @curious-mike-dvc,

thanks for your Request. I will add Support for Laravel 9 later this week.
Just keep an eye on this Issue to receive further information.

Best regards
Toby

**Comment by fjahn** [comment]
Any updates on this? I would be willing to give it a shot if you are too busy.

**Comment by TobyMaxham** [comment]
I build a Laravel 9 compatible version. This will be released today.
I will provide a changelog with an "upgrade note", since there might be some breaking changes in your application.

Since Laravel 9 is using the Symfony Mailer instead of the SwiftMailer I needed to rebuild some functionalities.

See the latest commit a455a06f94b9cc726feaf685151c584617634cc3 for details or for testing purpose. Currently not recommanded for production.

**Comment by TobyMaxham** [comment]
I will close this issue.

If there are any issues, please open a new issue for that.

[Released 22-04-11](https://github.com/TobyMaxham/laravel-dkim/releases/tag/v2.0.1)
